# Generated by Django 4.0.7 on 2022-08-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WSBPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('link', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
            ],
            options={
                'unique_together': {('ticker', 'name')},
            },
        ),
    ]
